AUGMENTATION     : True            # TECHNIQUE USED TO ARTIFICIALLY TO INCREASE THE SIZE OF THE TRAINING DATA SET BY ROTATION etc
IMAGE_SIZE       : [224,224,3]
BATCH_SIZE       : 10
INCLUDE_TOP      : False           #  WE ARE TRAINING VGG 16 TO BE A FEATURE EXTRACTORY NOT A CLASSIFIER
EPOCHS           : 10
CLASSES          : 2
WEIGHTS          : imagenet        # USE THE PRE TRAINED WEIGHTS ON THE IMAGENET DATASET
LEARNING_RATE    : 0.01

# INCLUDE_TOP  (BOOLEAN) -> ARE WE GOING TO USE VGG 16 FOR ITS ORIGINAL PURPOSE OF IMAGE CLASSIFCATION, WHILE SETTING IT TO FALSE
# WE ARE MAKING VGG16 TO EXTRACT USEFULL IMAGE FEATURES THAT CAN BE APPLIED TO THE CUSTOM DATA.

